"""empty message

Revision ID: 53da49b46132
Revises: cde5d6774b04
Create Date: 2021-06-15 20:20:02.930605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53da49b46132'
down_revision = 'cde5d6774b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
