"""deleted

Revision ID: 955b5c3015d2
Revises: fe371d6c03de
Create Date: 2021-06-15 20:24:25.945716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '955b5c3015d2'
down_revision = 'fe371d6c03de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='tester')
    op.drop_index('name', table_name='tester')
    op.drop_table('tester')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tester',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'tester', ['name'], unique=False)
    op.create_index('id', 'tester', ['id'], unique=False)
    # ### end Alembic commands ###
