"""empty message

Revision ID: cde5d6774b04
Revises: 601a9821bf48
Create Date: 2021-06-15 20:17:15.904539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde5d6774b04'
down_revision = '601a9821bf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
