"""empty message

Revision ID: fe371d6c03de
Revises: 53da49b46132
Create Date: 2021-06-15 20:22:44.405498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe371d6c03de'
down_revision = '53da49b46132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tester',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=30), nullable=False),
    sa.Column('mid_name', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('salary', sa.DECIMAL(), nullable=False),
    sa.Column('related_department', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['related_department'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('tester')
    op.drop_table('department')
    # ### end Alembic commands ###
